export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
// export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
// export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
